# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-25 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('money', models.IntegerField()),
                ('competitionState', models.IntegerField()),
                ('time', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
            ],
        ),
    ]
