# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('material', models.IntegerField()),
                ('rest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('competitionNumber', models.IntegerField()),
                ('peopleCount', models.IntegerField()),
                ('materialRed', models.IntegerField()),
                ('materialGreen', models.IntegerField()),
                ('materialBlue', models.IntegerField()),
                ('money', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('houses', models.IntegerField()),
                ('accounts', models.ManyToManyField(null=True, to='api.AccountModel')),
                ('machines', models.ManyToManyField(null=True, to='api.MachineModel')),
            ],
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='machineCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='peopleCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='competitionmodel',
            name='competitionState',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='competitionmodel',
            name='money',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='competitionmodel',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='teams',
            field=models.ManyToManyField(null=True, to='api.TeamModel'),
        ),
    ]
