# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171025_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='machinemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='teamNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='initialPasswordLength',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='materialNeedBlue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='materialNeedGreen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='materialNeedRed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='peopleCreated',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='teamNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='material',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='rest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='competitionNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='houses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='materialBlue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='materialGreen',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='materialRed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='money',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='peopleCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
