# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-31 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_competitionmodel_teamcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='ready',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='ready',
            field=models.IntegerField(null=True),
        ),
    ]
