# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-01 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171031_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='machineid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='machinerest',
            field=models.IntegerField(null=True),
        ),
    ]
