# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-09 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171101_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmodel',
            name='moneyNeedBlue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='moneyNeedGreen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='moneyNeedRed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='teamNumber',
            field=models.IntegerField(null=True),
        ),
    ]
