# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171109_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammodel',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='machines',
        ),
        migrations.AddField(
            model_name='information',
            name='trademachine',
            field=models.ManyToManyField(to='api.TeamModel'),
        ),
        migrations.AddField(
            model_name='information',
            name='tradestate',
            field=models.IntegerField(null=True),
        ),
    ]
