# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171109_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
