# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171109_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageCount',
            new_name='InformationCount',
        ),
        migrations.AddField(
            model_name='information',
            name='machineblue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='machinegreen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='machinered',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='materialblue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='materialgreen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='materialred',
            field=models.IntegerField(null=True),
        ),
    ]
