# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171109_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmodel',
            name='machinePriceBlue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='machinePriceGreen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='machinePriceRed',
            field=models.IntegerField(null=True),
        ),
    ]
