# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_adminaccountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='tradesucc',
            field=models.IntegerField(null=True),
        ),
    ]
