# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_information_tradesucc'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemodel',
            name='lock',
            field=models.IntegerField(null=True),
        ),
    ]
