# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-15 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_accountmodel_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='machineblue',
        ),
        migrations.RemoveField(
            model_name='information',
            name='machinegreen',
        ),
        migrations.RemoveField(
            model_name='information',
            name='machinered',
        ),
    ]
