# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-15 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20171115_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='trademachine',
            field=models.ManyToManyField(to='api.MachineModel'),
        ),
    ]
