# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20171115_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmodel',
            name='UPtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='UPmessage',
            field=models.IntegerField(null=True),
        ),
    ]
